name: CI - XGBoost Sleep Disorder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProject/sleep-health_life-style_preprocessing.csv"
  TARGET_VAR: "Sleep Disorder"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Train model with MLflow
      - name: Train model with MLflow
        working-directory: MLProject
        run: |
          mlflow run . --env-manager=local -P file_path=$CSV_URL

      - name: Debug mlruns directory contents
        run: |
          echo "mlruns directory contents:"
          ls -l mlruns/0/


      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -t mlruns/0/ | head -n 1)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"


      # Build Docker Image with the model
      - name: Build Docker Image
        run: |
          mlflow models build-docker --model-uri "runs:0/$RUN_ID/artifacts" --name "xgb_model_image:latest"


      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag xgb_model_image:latest ${{ secrets.DOCKER_HUB_USERNAME }}/xgb_model_image:latest

      # Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/xgb_model_image:latest
