name: CI - XGBoost Sleep Disorder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProject/sleep-health_life-style_preprocessing.csv"
  TARGET_VAR: "Sleep Disorder"
  MLFLOW_TRACKING_URI: "http://127.0.0.1/:5000" # Add this line if using a remote server

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          environment-file: MLProject/conda.yaml
          activate-environment: sleep-env

      - name: Train model with MLflow
        working-directory: MLProject
        run: |
          pip install mlflow
          mlflow run . --env-manager=local -P file_path=sleep-health_life-style_preprocessing.csv

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/xgboost_best_model.joblib

      - name: Build Docker Image
        run: |
          mlflow models build-docker -m "models:/SleepDisorderXGBoostModel/1" --name xgb_model_image

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag xgb_model_image ${{ secrets.DOCKER_HUB_USERNAME }}/xgb_model_image:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/xgb_model_image:latest
